PORT = 1729
MSG_LEN = 4
DIC_LIST = {
    "TAKE_SCREENSHOT": 0, "QUIT": 0, "EXIT": 0, "DIR": 1,
    "DELETE": 1, "COPY": 2, "EXECUTE": 1, "SEND_FILE": 1, "HISTORY": 1}
FILE_SEND_SIZE = 1024
LEN_REQ_PARS = 1
FIRST_REQ_PARS = 0
PARS = 1
NO_PARS = 0
COUNT_START = 0
BACK_SPLASH_ID = 92
COUNT_ADDER = 1
FIRST_PAR = 0
SECOND_PAR = 1
SOURCE_BASE_NAME = -1
